# syntax=docker/dockerfile:1
ARG BASE
FROM ${BASE}
ARG USER_ID
ARG ADD_APPS

RUN rm -rf ${DISTR_TMP}

RUN apt-get update --fix-missing && apt-get install -y build-essential python3 ${ADD_APPS}
RUN ln -s /usr/bin/python3 /usr/bin/python

ENV USERNAME=vivado
RUN adduser --disabled-password --gecos '' --uid ${USER_ID} ${USERNAME}
USER ${USERNAME}
