# syntax=docker/dockerfile:1
FROM vivado-distr

ARG USER_ID

ENV USERNAME=vivado
ENV XILINX_HOME=/root/.Xilinx

COPY install_config.txt ${XILINX_HOME}

RUN apt-get update --fix-missing && apt-get install -y libx11-6

RUN /tmp/wi/xsetup -b Install -a XilinxEULA,3rdPartyEULA,WebTalkTerms -c ${XILINX_HOME}/install_config.txt

