# syntax=docker/dockerfile:1
ARG BASE
FROM ${BASE}
ARG BASE_LIBS
ARG DISTR_DATA

ENV XILINX_HOME=/root/.Xilinx
RUN mkdir -p ${XILINX_HOME}

ENV DISTR_TMP=tmp/wi
RUN mkdir -p ${DISTR_TMP}

COPY ${DISTR_DATA}/ ${DISTR_TMP}/

RUN apt-get update --fix-missing && apt-get install -y ${BASE_LIBS}
