# syntax=docker/dockerfile:1
FROM vivado-install

ARG USER_ID

RUN rm -rf /tmp/wi

RUN apt-get update --fix-missing && apt-get install -y build-essential git python3
RUN ln -s /usr/bin/python3 /usr/bin/python

# RUN apt-get update --fix-missing && apt-get install -y mc

RUN adduser --disabled-password --gecos '' --uid ${USER_ID} ${USERNAME}
USER ${USERNAME}

