# syntax=docker/dockerfile:1
ARG BASE
FROM ${BASE}
ARG WOKRKSPACE

COPY ${WOKRKSPACE}/install_config.txt ${XILINX_HOME}

RUN ${DISTR_TMP}/xsetup -b Install -a XilinxEULA,3rdPartyEULA,WebTalkTerms -c ${XILINX_HOME}/install_config.txt
