# syntax=docker/dockerfile:1
FROM vivado-distr

ARG USER_ID

ENV USERNAME=vivado
ENV XILINX_HOME=/root/.Xilinx

COPY auth.sh /tmp/

RUN adduser --disabled-password --gecos '' --uid ${USER_ID} ${USERNAME}
USER ${USERNAME}

